### ISSUE TITLE
Unable to resolve the dependencies for Mongodb-binding i.e. mongodb-async-driver

### ISSUE THREAD

**Issue by adnavare** [allanbank/mongodb-async-driver#35]
Hi,

I am trying to run YCSB with mongodb-async driver. I have installed maven (3.6.0), added proxies inside settings.xml,but still I am getting the following error

Failed to execute goal on project mongodb-binding: Could not resolve dependencies for project com.yahoo.ycsb:mongodb-binding:jar:0.16.0-SNAPSHOT: Failed to collect dependencies at com.allanbank:mongodb-async-driver:jar:2.10.1: Failed to read artifact descriptor for com.allanbank:mongodb-async-driver:jar:2.10.1: Could not transfer artifact com.allanbank:mongodb-async-driver:pom:2.10.1 from/to allanbank (http://www.allanbank.com/repo/): Connect to www.allanbank.com:80 [www.allanbank.com/206.210.70.161] failed: Connection timed out (Connection timed out) -> [Help 1]

Can someone point me, what might be going wrong here?

**Comment by allanbank** [comment]
I commented on your ticket here: https://github.com/brianfrankcooper/YCSB/issues/1278.
